In [1]:
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import LabelEncoder
from sklearn.feature_extraction.text import CountVectorizer

In [3]:
from keras.models import Sequential
from keras.layers import Dense

In [4]:
df = pd.read_csv('fake reviews dataset.csv')

In [5]:
df.head()

category  rating label  \
0  Home_and_Kitchen_5     5.0    CG   
1  Home_and_Kitchen_5     5.0    CG   
2  Home_and_Kitchen_5     5.0    CG   
3  Home_and_Kitchen_5     1.0    CG   
4  Home_and_Kitchen_5     5.0    CG   

                                               text_  
0  Love this!  Well made, sturdy, and very comfor...  
1  love it, a great upgrade from the original.  I...  
2  This pillow saved my back. I love the look and...  
3  Missing information on how to use it, but it i...  
4  Very nice set. Good quality. We have had the s...

In [6]:
le  =LabelEncoder()

In [7]:
df['label'] = le.fit_transform(df['label'])

In [9]:
cv = CountVectorizer()

In [10]:
df['label'].value_counts()

label
0    20216
1    20216
Name: count, dtype: int64

In [11]:
m = cv.fit_transform(df['text_']).toarray()

In [14]:
len(m)

40432

In [19]:
# Using CountVectorizer

In [15]:
x=m
y = df['label']

In [16]:
x = x[0:10000,:]

In [17]:
y = y.iloc[0:10000]

In [18]:
print(x)
print(y)

[[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]
0       0
1       0
2       0
3       0
4       0
       ..
9995    1
9996    1
9997    1
9998    1
9999    1
Name: label, Length: 10000, dtype: int32


In [19]:
x_train, x_test, y_train, y_test = train_test_split(x,y,test_size=0.2,random_state=46)

In [20]:
model = Sequential()
# model.add(Dense(42026,activation='relu'))
# model.add(Dense(42026,activation='relu'))
# model.add(Dense(42026,activation='relu'))
model.add(Dense(1313,activation='relu'))
model.add(Dense(1313,activation='relu'))
model.add(Dense(733,activation='relu'))
model.add(Dense(1,activation='sigmoid'))


In [21]:
model.compile(optimizer='adam' , loss='binary_crossentropy', metrics=['accuracy'])

In [ ]:
model.fit(x_train,y_train,epochs=10)

Epoch 1/10
250/250 ━━━━━━━━━━━━━━━━━━━━ 162s 613ms/step - accuracy: 0.8106 - loss: 0.3794
Epoch 2/10
250/250 ━━━━━━━━━━━━━━━━━━━━ 157s 628ms/step - accuracy: 0.9665 - loss: 0.0974
Epoch 3/10
 36/250 ━━━━━━━━━━━━━━━━━━━━ 2:14 628ms/step - accuracy: 0.9926 - loss: 0.0387

In [20]:
pred = model.predict(x_test)

63/63 ━━━━━━━━━━━━━━━━━━━━ 3s 44ms/step


In [21]:
for i in range(len(pred)):
    if pred[i]>=0.5:
        pred[i]=1
    else:
        pred[i]=0

In [22]:
for i in range(len(pred)):
    print(pred[i],y_test.iloc[i],sep='---------------')

[0.]---------------0
[1.]---------------0
[0.]---------------0
[0.]---------------0
[1.]---------------1
[0.]---------------0
[0.]---------------0
[1.]---------------1
[1.]---------------1
[1.]---------------1
[1.]---------------1
[0.]---------------0
[0.]---------------0
[0.]---------------0
[1.]---------------0
[1.]---------------0
[0.]---------------0
[0.]---------------0
[0.]---------------0
[0.]---------------0
[0.]---------------0
[1.]---------------1
[1.]---------------1
[0.]---------------0
[1.]---------------0
[0.]---------------0
[1.]---------------1
[1.]---------------1
[1.]---------------1
[1.]---------------1
[0.]---------------0
[1.]---------------0
[0.]---------------0
[0.]---------------0
[0.]---------------0
[1.]---------------1
[0.]---------------0
[0.]---------------0
[1.]---------------1
[1.]---------------1
[0.]---------------0
[1.]---------------1
[0.]---------------0
[1.]---------------1
[0.]---------------0
[1.]---------------1
[0.]---------------0
[1.]---------

In [23]:
from sklearn.metrics import classification_report

In [24]:
print(classification_report(y_test,pred))

              precision    recall  f1-score   support

           0       0.90      0.90      0.90       986
           1       0.90      0.90      0.90      1014

    accuracy                           0.90      2000
   macro avg       0.90      0.90      0.90      2000
weighted avg       0.90      0.90      0.90      2000



In [20]:
#Using TfidfVectorizer

In [12]:
x=k
y = df['label']

In [13]:
x = x[0:10000,:]

In [14]:
y = y.iloc[0:10000]

In [15]:
print(x)
print(y)

[[0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]]
0       0
1       0
2       0
3       0
4       0
       ..
9995    1
9996    1
9997    1
9998    1
9999    1
Name: label, Length: 10000, dtype: int32


In [16]:
x_train, x_test, y_train, y_test = train_test_split(x,y,test_size=0.2,random_state=46)

In [17]:
model = Sequential()
# model.add(Dense(42026,activation='relu'))
# model.add(Dense(42026,activation='relu'))
# model.add(Dense(42026,activation='relu'))
model.add(Dense(1313,activation='relu'))
model.add(Dense(1313,activation='relu'))
model.add(Dense(733,activation='relu'))
model.add(Dense(1,activation='sigmoid'))


In [18]:
model.compile(optimizer='adam' , loss='binary_crossentropy', metrics=['accuracy'])

In [19]:
model.fit(x_train,y_train,epochs=10)

Epoch 1/10
250/250 ━━━━━━━━━━━━━━━━━━━━ 146s 545ms/step - accuracy: 0.8128 - loss: 0.3862
Epoch 2/10
250/250 ━━━━━━━━━━━━━━━━━━━━ 139s 557ms/step - accuracy: 0.9736 - loss: 0.0752
Epoch 3/10
250/250 ━━━━━━━━━━━━━━━━━━━━ 138s 550ms/step - accuracy: 0.9929 - loss: 0.0203
Epoch 4/10
250/250 ━━━━━━━━━━━━━━━━━━━━ 138s 550ms/step - accuracy: 0.9976 - loss: 0.0067
Epoch 5/10
250/250 ━━━━━━━━━━━━━━━━━━━━ 137s 549ms/step - accuracy: 0.9989 - loss: 0.0075
Epoch 6/10
250/250 ━━━━━━━━━━━━━━━━━━━━ 137s 548ms/step - accuracy: 0.9952 - loss: 0.0149
Epoch 7/10
250/250 ━━━━━━━━━━━━━━━━━━━━ 137s 549ms/step - accuracy: 0.9994 - loss: 0.0020
Epoch 8/10
250/250 ━━━━━━━━━━━━━━━━━━━━ 137s 546ms/step - accuracy: 0.9993 - loss: 0.0016
Epoch 9/10
250/250 ━━━━━━━━━━━━━━━━━━━━ 137s 547ms/step - accuracy: 1.0000 - loss: 8.4500e-06
Epoch 10/10
250/250 ━━━━━━━━━━━━━━━━━━━━ 137s 547ms/step - accuracy: 1.0000 - loss: 3.3917e-06


In [20]:
pred = model.predict(x_test)

63/63 ━━━━━━━━━━━━━━━━━━━━ 3s 45ms/step


In [21]:
for i in range(len(pred)):
    if pred[i]>=0.5:
        pred[i]=1
    else:
        pred[i]=0

In [24]:
print(classification_report(y_test,pred))

              precision    recall  f1-score   support

           0       0.86      0.92      0.89       986
           1       0.92      0.85      0.88      1014

    accuracy                           0.89      2000
   macro avg       0.89      0.89      0.89      2000
weighted avg       0.89      0.89      0.89      2000



In [25]:
for i in range(len(pred)):
    print(pred[i],y_test.iloc[i],sep='---------------')

[0.]---------------0
[0.]---------------0
[0.]---------------0
[0.]---------------0
[1.]---------------1
[0.]---------------0
[0.]---------------0
[1.]---------------1
[1.]---------------1
[1.]---------------1
[1.]---------------1
[0.]---------------0
[0.]---------------0
[0.]---------------0
[0.]---------------0
[1.]---------------0
[0.]---------------0
[0.]---------------0
[0.]---------------0
[0.]---------------0
[0.]---------------0
[1.]---------------1
[1.]---------------1
[0.]---------------0
[1.]---------------0
[0.]---------------0
[1.]---------------1
[1.]---------------1
[1.]---------------1
[1.]---------------1
[0.]---------------0
[1.]---------------0
[0.]---------------0
[0.]---------------0
[0.]---------------0
[1.]---------------1
[0.]---------------0
[0.]---------------0
[1.]---------------1
[1.]---------------1
[0.]---------------0
[1.]---------------1
[0.]---------------0
[1.]---------------1
[0.]---------------0
[1.]---------------1
[0.]---------------0
[1.]---------

In [26]:
#Using SVM

In [27]:
from sklearn.svm import SVC
clf = SVC(kernel='linear')

clf.fit(x_train, y_train)

SVC(kernel='linear')

In [28]:
pred=clf.predict(x_test)

In [29]:
print(classification_report(y_test,pred))

              precision    recall  f1-score   support

           0       0.90      0.88      0.89       986
           1       0.89      0.91      0.90      1014

    accuracy                           0.90      2000
   macro avg       0.90      0.89      0.89      2000
weighted avg       0.90      0.90      0.89      2000

