In [9]:
from keras.models import Model,Sequential
from keras.layers import Dense,Dropout,Conv2D,MaxPool2D

In [11]:
from tensorflow.keras.preprocessing.image import ImageDataGenerator

In [13]:
train_datagen=ImageDataGenerator(rescale=1/255)


In [15]:
train_generator = train_datagen.flow_from_directory(
        'C:\\Users\\yjyas\\CNN\\food20dataset\\train_set',
        target_size=(224, 224),
        batch_size=64)

Found 1400 images belonging to 20 classes.


In [17]:
print(train_generator.class_indices)

{'biriyani': 0, 'bisibelebath': 1, 'butternaan': 2, 'chaat': 3, 'chappati': 4, 'dhokla': 5, 'dosa': 6, 'gulab jamun': 7, 'halwa': 8, 'idly': 9, 'kathi roll': 10, 'meduvadai': 11, 'noodles': 12, 'paniyaram': 13, 'poori': 14, 'samosa': 15, 'tandoori chicken': 16, 'upma': 17, 'vada pav': 18, 'ven pongal': 19}


In [19]:
test_datagen=ImageDataGenerator(rescale=1/255)

In [21]:
test_generator = test_datagen.flow_from_directory(
        'C:\\Users\\yjyas\\CNN\\food20dataset\\test_set',
        target_size=(224, 224),
        batch_size=64)

Found 600 images belonging to 20 classes.


In [23]:
print(test_generator.class_indices)

{'biriyani': 0, 'bisibelebath': 1, 'butternaan': 2, 'chaat': 3, 'chappati': 4, 'dhokla': 5, 'dosa': 6, 'gulab jamun': 7, 'halwa': 8, 'idly': 9, 'kathi roll': 10, 'meduvadai': 11, 'noodles': 12, 'paniyaram': 13, 'poori': 14, 'samosa': 15, 'tandoori chicken': 16, 'upma': 17, 'vada pav': 18, 'ven pongal': 19}


In [85]:
test_generator.classes

array([ 0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,
        0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  1,  1,  1,  1,
        1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,
        1,  1,  1,  1,  1,  1,  1,  1,  1,  2,  2,  2,  2,  2,  2,  2,  2,
        2,  2,  2,  2,  2,  2,  2,  2,  2,  2,  2,  2,  2,  2,  2,  2,  2,
        2,  2,  2,  2,  2,  3,  3,  3,  3,  3,  3,  3,  3,  3,  3,  3,  3,
        3,  3,  3,  3,  3,  3,  3,  3,  3,  3,  3,  3,  3,  3,  3,  3,  3,
        3,  4,  4,  4,  4,  4,  4,  4,  4,  4,  4,  4,  4,  4,  4,  4,  4,
        4,  4,  4,  4,  4,  4,  4,  4,  4,  4,  4,  4,  4,  4,  5,  5,  5,
        5,  5,  5,  5,  5,  5,  5,  5,  5,  5,  5,  5,  5,  5,  5,  5,  5,
        5,  5,  5,  5,  5,  5,  5,  5,  5,  5,  6,  6,  6,  6,  6,  6,  6,
        6,  6,  6,  6,  6,  6,  6,  6,  6,  6,  6,  6,  6,  6,  6,  6,  6,
        6,  6,  6,  6,  6,  6,  7,  7,  7,  7,  7,  7,  7,  7,  7,  7,  7,
        7,  7,  7,  7,  7

In [17]:
from keras.models import Model,Sequential
from keras.layers import Dense,Flatten,Conv2D,MaxPooling2D,Dropout

In [45]:
model = Sequential()
model.add(Conv2D(filters = 64,kernel_size=(5,5),activation='relu',input_shape=(224,224,3), padding='Same'))
model.add(MaxPooling2D(pool_size=(3,3)))
model.add(Dropout(0.25))
model.add(Conv2D(filters = 128,kernel_size=(5,5),activation='relu',input_shape=(224,224,3),padding='Same'))
model.add(MaxPooling2D(pool_size=(3,3)))
model.add(Dropout(0.25))
model.add(Conv2D(filters = 128,kernel_size=(3,3),activation='relu',input_shape=(224,224,3),strides=1, padding='Same'))
model.add(MaxPooling2D(pool_size=(2,2)))
model.add(Dropout(0.25))
model.add(Flatten())
model.add(Dense(256,activation='relu'))
# model.add(Dropout(0.2))
model.add(Dense(20,activation='softmax'))

In [47]:
model.compile(optimizer='adam',loss='categorical_crossentropy',metrics=['accuracy'])
model.fit(train_generator,epochs=50)

Epoch 1/50
22/22 ━━━━━━━━━━━━━━━━━━━━ 109s 5s/step - accuracy: 0.0435 - loss: 3.4530
Epoch 2/50
22/22 ━━━━━━━━━━━━━━━━━━━━ 103s 5s/step - accuracy: 0.0714 - loss: 2.9955
Epoch 3/50
22/22 ━━━━━━━━━━━━━━━━━━━━ 109s 5s/step - accuracy: 0.0899 - loss: 2.9501
Epoch 4/50
22/22 ━━━━━━━━━━━━━━━━━━━━ 108s 5s/step - accuracy: 0.1453 - loss: 2.7617
Epoch 5/50
22/22 ━━━━━━━━━━━━━━━━━━━━ 109s 5s/step - accuracy: 0.1881 - loss: 2.5975
Epoch 6/50
22/22 ━━━━━━━━━━━━━━━━━━━━ 110s 5s/step - accuracy: 0.1968 - loss: 2.5771
Epoch 7/50
22/22 ━━━━━━━━━━━━━━━━━━━━ 109s 5s/step - accuracy: 0.2117 - loss: 2.4935
Epoch 8/50
22/22 ━━━━━━━━━━━━━━━━━━━━ 125s 6s/step - accuracy: 0.2864 - loss: 2.2806
Epoch 9/50
22/22 ━━━━━━━━━━━━━━━━━━━━ 129s 6s/step - accuracy: 0.3902 - loss: 2.0294
Epoch 10/50
22/22 ━━━━━━━━━━━━━━━━━━━━ 119s 5s/step - accuracy: 0.5281 - loss: 1.5298
Epoch 11/50
22/22 ━━━━━━━━━━━━━━━━━━━━ 111s 5s/step - accuracy: 0.6604 - loss: 1.1962
Epoch 12/50
22/22 ━━━━━━━━━━━━━━━━━━━━ 118s 5s/step - accuracy:

In [35]:
pred1 = model.predict(test_generator)

10/10 ━━━━━━━━━━━━━━━━━━━━ 24s 2s/step


In [43]:
import numpy as np
for i in range(10):
    print(np.argmax(pred1[i]))

4
15
6
9
17
3
10
3
19
10


In [1]:
#--------------------------------------------------------

In [3]:
from tensorflow.keras.models import load_model

In [5]:
model = load_model('food.keras')

In [7]:
model.compile(optimizer='adam',loss='categorical_crossentropy',metrics=['accuracy'])

In [63]:
pred = model.predict(test_generator)

10/10 ━━━━━━━━━━━━━━━━━━━━ 34s 3s/step


In [65]:
print(pred[0])

[3.5353747e-08 8.9105619e-11 4.2991335e-09 1.3033307e-08 9.9993348e-01
 1.7770235e-08 1.0257710e-07 2.0386597e-10 3.4123063e-06 1.4917857e-10
 1.9491470e-06 4.7749255e-10 1.9990152e-06 1.1372256e-08 1.7084718e-05
 7.6200584e-09 3.2693937e-12 4.0403738e-05 1.3045074e-06 2.2740661e-08]


In [67]:
for i  in range(len(pred)):
    pred[i] = np.argmax(pred[i])

In [71]:
len(pred)

600

In [113]:
for i  in range(len(pred)):
    pred1[i] = pred[i][0]

In [111]:
pred1 = np.ones(600)

In [97]:
pred[0].shape

(20,)

In [117]:
print(pred1[0])

4.0


In [103]:
test_generator.classes[0]

0

In [119]:
test_generator.classes.shape

(600,)

In [121]:
pred1.shape

(600,)

In [123]:
from sklearn.metrics import classification_report

In [125]:
print(classification_report(pred1,test_generator.classes))

              precision    recall  f1-score   support

         0.0       0.00      0.00      0.00        21
         1.0       0.00      0.00      0.00        25
         2.0       0.03      0.06      0.04        18
         3.0       0.03      0.04      0.04        26
         4.0       0.00      0.00      0.00        39
         5.0       0.03      0.02      0.02        56
         6.0       0.03      0.04      0.04        25
         7.0       0.03      0.05      0.04        19
         8.0       0.07      0.08      0.07        26
         9.0       0.10      0.14      0.12        21
        10.0       0.07      0.06      0.06        32
        11.0       0.10      0.10      0.10        29
        12.0       0.03      0.05      0.04        21
        13.0       0.07      0.07      0.07        28
        14.0       0.10      0.07      0.08        44
        15.0       0.00      0.00      0.00        24
        16.0       0.07      0.06      0.07        31
        17.0       0.07    

In [127]:
model.evaluate(test_generator)

10/10 ━━━━━━━━━━━━━━━━━━━━ 30s 3s/step - accuracy: 0.5045 - loss: 5.2570


[5.2726216316223145, 0.5116666555404663]

In [131]:
for i in range(len(pred1)):
    print(pred1[i],test_generator.classes[i],sep='---------------------------')

4.0---------------------------0
16.0---------------------------0
14.0---------------------------0
6.0---------------------------0
5.0---------------------------0
4.0---------------------------0
12.0---------------------------0
14.0---------------------------0
14.0---------------------------0
17.0---------------------------0
19.0---------------------------0
8.0---------------------------0
5.0---------------------------0
8.0---------------------------0
1.0---------------------------0
19.0---------------------------0
13.0---------------------------0
4.0---------------------------0
17.0---------------------------0
18.0---------------------------0
9.0---------------------------0
1.0---------------------------0
3.0---------------------------0
13.0---------------------------0
17.0---------------------------0
2.0---------------------------0
1.0---------------------------0
10.0---------------------------0
10.0---------------------------0
2.0---------------------------0
16.0---------------------

In [129]:
model.evaluate(train_generator)

C:\Users\yjyas\anaconda3\Lib\site-packages\keras\src\trainers\data_adapters\py_dataset_adapter.py:121: UserWarning: Your `PyDataset` class should call `super().__init__(**kwargs)` in its constructor. `**kwargs` can include `workers`, `use_multiprocessing`, `max_queue_size`. Do not pass these arguments to `fit()`, as they will be ignored.
  self._warn_if_super_not_called()


22/22 ━━━━━━━━━━━━━━━━━━━━ 66s 3s/step - accuracy: 0.9988 - loss: 0.0036


[0.0051559749990701675, 0.9978571534156799]

In [73]:
pred[1]

array([16., 16., 16., 16., 16., 16., 16., 16., 16., 16., 16., 16., 16.,
       16., 16., 16., 16., 16., 16., 16.], dtype=float32)

In [75]:
pred.shape

(600, 20)

In [45]:
for i in range(1):
    print(test_generator[i], pred[i])

(array([[[[0.92549026, 0.86274517, 0.80392164],
         [0.91372555, 0.8470589 , 0.7686275 ],
         [0.8980393 , 0.81568635, 0.7411765 ],
         ...,
         [0.9333334 , 0.8588236 , 0.79215693],
         [0.9333334 , 0.86274517, 0.7843138 ],
         [0.91372555, 0.8431373 , 0.7568628 ]],

        [[0.9294118 , 0.8588236 , 0.80392164],
         [0.92549026, 0.854902  , 0.7607844 ],
         [0.9176471 , 0.8313726 , 0.7411765 ],
         ...,
         [0.8862746 , 0.80392164, 0.6901961 ],
         [0.8980393 , 0.80392164, 0.70980394],
         [0.8980393 , 0.8117648 , 0.72156864]],

        [[0.92549026, 0.854902  , 0.77647066],
         [0.9058824 , 0.82745105, 0.73333335],
         [0.96470594, 0.86274517, 0.8117648 ],
         ...,
         [0.8862746 , 0.8078432 , 0.6784314 ],
         [0.90196085, 0.8078432 , 0.7137255 ],
         [0.8941177 , 0.81568635, 0.7176471 ]],

        ...,

        [[0.95294124, 0.7372549 , 0.61960787],
         [1.        , 0.9450981 , 0.87843144

In [47]:
pred[0]

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1.], dtype=float32)

In [61]:
model.summary()

Model: "sequential_5"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━┓
┃ Layer (type)                         ┃ Output Shape                ┃         Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━┩
│ conv2d_7 (Conv2D)                    │ (None, 224, 224, 64)        │           4,864 │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ max_pooling2d_3 (MaxPooling2D)       │ (None, 74, 74, 64)          │               0 │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ dropout_3 (Dropout)                  │ (None, 74, 74, 64)          │               0 │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ conv2d_8 (Conv2D)                    │ (None, 74, 74, 128)         │         204,928 │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ max_pooling2d_4 (MaxPooling2D)       │ (None, 24, 24, 128)         │               0 │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ dropout_4 (Dropout)                  │ (None, 24, 24, 128)         │               0 │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ conv2d_9 (Conv2D)                    │ (None, 24, 24, 128)         │         147,584 │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ max_pooling2d_5 (MaxPooling2D)       │ (None, 12, 12, 128)         │               0 │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ dropout_5 (Dropout)                  │ (None, 12, 12, 128)         │               0 │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ flatten_1 (Flatten)                  │ (None, 18432)               │               0 │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ dense_2 (Dense)                      │ (None, 256)                 │       4,718,848 │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ dense_3 (Dense)                      │ (None, 20)                  │           5,140 │
└──────────────────────────────────────┴─────────────────────────────┴─────────────────┘

 Total params: 5,081,364 (19.38 MB)

 Trainable params: 5,081,364 (19.38 MB)

 Non-trainable params: 0 (0.00 B)

In [1]:
from tensorflow.keras.models import load_model

In [5]:
model = load_model('food_img.keras')

In [7]:
model.compile(optimizer='adam',loss='categorical_crossentropy',metrics=['accuracy'])

In [23]:
model.evaluate(test_generator)

C:\Users\yjyas\anaconda3\Lib\site-packages\keras\src\trainers\data_adapters\py_dataset_adapter.py:121: UserWarning: Your `PyDataset` class should call `super().__init__(**kwargs)` in its constructor. `**kwargs` can include `workers`, `use_multiprocessing`, `max_queue_size`. Do not pass these arguments to `fit()`, as they will be ignored.
  self._warn_if_super_not_called()


10/10 ━━━━━━━━━━━━━━━━━━━━ 34s 3s/step - accuracy: 0.5358 - loss: 4.9428


[4.998066425323486, 0.5249999761581421]

In [25]:
model.summary()

Model: "sequential"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━┓
┃ Layer (type)                         ┃ Output Shape                ┃         Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━┩
│ conv2d (Conv2D)                      │ (None, 224, 224, 64)        │           4,864 │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ max_pooling2d (MaxPooling2D)         │ (None, 74, 74, 64)          │               0 │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ dropout (Dropout)                    │ (None, 74, 74, 64)          │               0 │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ conv2d_1 (Conv2D)                    │ (None, 74, 74, 128)         │         204,928 │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ max_pooling2d_1 (MaxPooling2D)       │ (None, 24, 24, 128)         │               0 │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ dropout_1 (Dropout)                  │ (None, 24, 24, 128)         │               0 │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ conv2d_2 (Conv2D)                    │ (None, 24, 24, 128)         │         147,584 │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ max_pooling2d_2 (MaxPooling2D)       │ (None, 12, 12, 128)         │               0 │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ dropout_2 (Dropout)                  │ (None, 12, 12, 128)         │               0 │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ flatten (Flatten)                    │ (None, 18432)               │               0 │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ dense (Dense)                        │ (None, 256)                 │       4,718,848 │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ dense_1 (Dense)                      │ (None, 20)                  │           5,140 │
└──────────────────────────────────────┴─────────────────────────────┴─────────────────┘

 Total params: 5,081,364 (19.38 MB)

 Trainable params: 5,081,364 (19.38 MB)

 Non-trainable params: 0 (0.00 B)